### ISSUE TITLE
This isn’t pocketmine-4

### ISSUE THREAD

**Issue by iZeaoGamer** [vecnavium-pm-pl/CustomMessages#1]
So, I’ve seen your plugins you’ve made, and was wondering why you added the API version: 4.0, if the codes its self aren’t for pocketmine-4?
The plugin will not work on PMMP 4 due to it not being updated properly.

For example, onEnable() onLoad() and onDisable() should both be protected, not public.

another example, is you should use Wold instead of Level, so the namespace should be: pocketmine\world\World, and not pocketmine\level\Level.

**Comment by Vecnavium** [comment]
This plugin is for API 4.0.0 and I have tested it before even considering on open sourcing it, it worked just fine for me on both two supported features.
Although, you do have a point for both things you told me about the onEnable, Load and Disable function and the world namespaces that I should change, I will have them both modified later today.

**Comment by iZeaoGamer** [comment]
Also, in the configuration, what’s the point of adding two of the same or similar options?

1. Says Disabled.
2. says Enabled. 

What’s the difference? Wouldn’t it be better just adding “Enabled”?

**Comment by Vecnavium** [comment]
I have removed the namespaces for pocketmine\world\World as it had no use.

Related to the configuration, you have a great point, I won't go into depth of what my point was for doing that but you suggesting that was valid so I did so and left only Enabled and removed Disabled.
