### ISSUE TITLE
WhitelistedServer message not working

### ISSUE THREAD

**Issue by NhanAZ** [vecnavium-pm-pl/CustomMessages#2]
**Describe the bug**
WhitelistedServer message not working
Instead of getting the CustomMessages plugin's custom message, I'm getting the default message

**To Reproduce**
- /whitelist on
- Join Server

**Expected behavior**
Receive custom notifications when a server is whitelisted

**CustomMessages plugin information**
- Plugin Version: 1.0.0

**Screenshots**

<details>

![](https://raw.githubusercontent.com/NhanAZ/Images/master/whitelistednotworking.png)
![](https://raw.githubusercontent.com/NhanAZ/Images/master/defaultmessage.jpg)

</details>

**Additional context**
N/A

**Comment by KingboiDre** [comment]
You leaked your ip - https://raw.githubusercontent.com/NhanAZ/Images/master/whitelistednotworking.png

**Comment by DretooFuni** [comment]
Ensure you have { https://github.com/vecnavium-pm-pl/CustomMessages/blob/26c63074d44c6b7c6e6f5f4bbb55d456defe6633/resources/config.yml#L16 } set  and the message have like https://github.com/vecnavium-pm-pl/CustomMessages/blob/26c63074d44c6b7c6e6f5f4bbb55d456defe6633/resources/config.yml#L17

**Comment by AGTHARN** [comment]
> You leaked your ip - https://raw.githubusercontent.com/NhanAZ/Images/master/whitelistednotworking.png

It's a private IP.

**Comment by DretooFuni** [comment]
> 
> It's a private IP.

:))

**Comment by NhanAZ** [comment]
> Ensure you have {
> 
> https://github.com/vecnavium-pm-pl/CustomMessages/blob/26c63074d44c6b7c6e6f5f4bbb55d456defe6633/resources/config.yml#L16
> 
> } set and the message have like
> https://github.com/vecnavium-pm-pl/CustomMessages/blob/26c63074d44c6b7c6e6f5f4bbb55d456defe6633/resources/config.yml#L17

I use the plugin's default configuration

**Comment by Vecnavium** [comment]
The issue has been fixed on [v1.0.1](https://github.com/vecnavium-pm-pl/CustomMessages/releases/tag/v1.0.1)
